---
title: "Insurance_Value_Analysis"
author: "Marius Munschek"
date: "2025-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=TRUE, fig.width=10, fig.height=6, dpi=300, cache=TRUE, cache.lazy=FALSE, cache.path="cache/", fig.path="figures/", out.width="100%", out.height="100%")

source("C:/Users/mm68tulo/Documents/R/functions/myfunctions.R")

theme_set(theme_custom())
```

```{r}
library(dplyr)
library(ggplot2)
library(MCMCpack)
```

```{r}
# define model for RP ~ sowndiv
fit_rp <- brm(RP ~ log2(sowndiv) + (1|block), data = synthDat, )

# plot regression
c_sown_rp <- conditional_effects(fit_rp)
plot_sown_rp_data <- c_sown_rp[[1]]

p_sown_rp <- ggplot() +
  geom_point(
    data   = synthDat,
    aes(x  = sowndiv, y = RP),
    alpha  = 0.5,
    size   = 2,
    shape  = 21,
    fill   = "#0072B2",
    colour = "#004C70",
    stroke = 0.4,
    position = position_jitter(width = 0.12, height = 0)
  ) +
  geom_line(
    data     = plot_sown_rp_data,
    aes(x    = 2^log2(sowndiv), y = estimate__),
    colour   = "#0072B2",
    linewidth = 0.8
  ) +
  geom_ribbon(
    data  = plot_sown_rp_data,
    aes(x = 2^log2(sowndiv), ymin = lower__, ymax = upper__),
    fill  = "#0072B2",
    alpha = 0.15
  ) +
  scale_x_continuous(
    breaks = c(1, 2, 4, 8, 16),
    labels = c(1, 2, 4, 8, 16),
    expand = expansion(mult = c(0.02, 0.02))
  ) +
  labs(
    x = "Sown plant species richness",
    y = expression("Risk premium; € ha"^{-1}*" yr"^{-1}*"")
  ) +
  coord_cartesian(clip = "off") +
  theme_custom() +
  theme(aspect.ratio = 0.6)

p_sown_rp

ggsave(
  filename = "Fig_sown_RP.png",
  plot     = p_sown_rp,
  width    = 8,     # in inches; adjust to Nature’s figure width
  height   = 5,
  units    = "in",
  device   = "png",
  dpi      = 300,
  path = "C:/Users/mm68tulo/Desktop/Jena Chapter/Data Analysis/3_Graphs/" 
)


# calculate effect size of insurance
post <- as_draws_df(fit_rp)

insurance_draws <- -post$b_log2sowndiv

insurance_summary <- tibble(
  mean = mean(insurance_draws),
  lwr  = quantile(insurance_draws, 0.025),
  upr  = quantile(insurance_draws, 0.975)
)

insurance_summary


```


```{r}
by_SR_pub <- by_SR %>%
  dplyr::select(
    sowndiv,
    mu_SR,
    CV_SR,
    RP_SR,
    CE_SR,
    insurance_RP,
    insurance_CE
  ) %>% 
  left_join(insurance_post, by = join_by(sowndiv))


write.csv(by_SR_pub, "C:/Users/mm68tulo/Desktop/Jena Chapter/Data Analysis/1_Data/by_SR_publication.csv", row.names = FALSE)
```

```{r}
# calculate uncertainties for plotting
ins <- synthDat %>%
  dplyr::select(plotcode, sowndiv, RP)

d0 <- min(ins$sowndiv)

bb_insurance <- function(data, d0, n_draws = 4000) {
  
  richness_levels <- sort(unique(data$sowndiv))
  
  draws <- lapply(1:n_draws, function(i) {
    
    # weighted means per richness
    rp_means <- sapply(richness_levels, function(d) {
      rp_d <- data$RP[data$sowndiv == d]
      w <- as.numeric(rdirichlet(1, rep(1, length(rp_d))))
      sum(w * rp_d)
    })
    
    names(rp_means) <- richness_levels
    
    tibble(
      sowndiv = richness_levels,
      insurance_RP = rp_means[as.character(d0)] - rp_means
    )
  })
  
  bind_rows(draws, .id = "draw")
}

# run model
bb_draws <- bb_insurance(ins, d0)


insurance_post <- bb_draws %>%
  group_by(sowndiv) %>%
  summarise(
    mean = mean(insurance_RP),
    lwr  = quantile(insurance_RP, 0.025),
    upr  = quantile(insurance_RP, 0.975),
    .groups = "drop"
  )


p_sown_insurance <- ggplot(
  insurance_post,
  aes(x = factor(sowndiv), y = mean)
) +
  
  # points (matched aesthetics)
  geom_point(
    size   = 2.5,
    shape  = 21,
    fill   = "#0072B2",
    colour = "#004C70",
    stroke = 0.4
  ) +
  
  # credible intervals
  geom_errorbar(
    aes(ymin = lwr, ymax = upr),
    width  = 0.15,
    colour = "#004C70",
    linewidth = 0.5
  ) +
  
  # zero reference line
  geom_hline(
    yintercept = 0,
    linetype   = "dashed",
    colour     = "grey50",
    linewidth  = 0.6
  ) +
  
  scale_x_discrete(
    limits = c("1", "2", "4", "8", "16")
  ) +
  
  labs(
    x = "Sown plant species richness",
    y = expression("Insurance value; € ha"^{-1}*" yr"^{-1}*"")
  ) +
  
  coord_cartesian(clip = "off") +
  
  theme_custom() +
  theme(
    aspect.ratio = 0.6
  )


ggsave(
  filename = "Fig_sown_insurance.png",
  plot     = p_sown_insurance,
  width    = 8,     # in inches; adjust to Nature’s figure width
  height   = 5,
  units    = "in",
  device   = "png",
  dpi      = 300,
  path = "C:/Users/mm68tulo/Desktop/Jena Chapter/Data Analysis/3_Graphs/")

```

